### ISSUE TITLE
osmanozdemir1 - The Club NFT owner at the end of the league might be different from the owner at the moment when the Merkle Tree is generated, leading to a different prize recipient.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-footium-judging#29]
osmanozdemir1

medium

# The Club NFT owner at the end of the league might be different from the owner at the moment when the Merkle Tree is generated, leading to a different prize recipient.

## Summary
Prize recipients are decided based on the club NFT owners, and stored in a Merkle tree which is created off-chain. There will be a time lag between the end of a league and the generation of the Merkle tree. The owner of the same NFT at these two different timestamps might be different, which will lead to unfair prize distribution.

## Vulnerability Detail
Club NFTs give users the right to play the Footium game. Users earn prizes by playing games, and these prize amounts are stored in a Merkle tree which is generated off-chain at the end of a season.

[https://github.com/sherlock-audit/2023-12-footium/blob/main/footium-eth-shareable/contracts/FootiumPrizeDistributor.sol#L109C2-L130C10](https://github.com/sherlock-audit/2023-12-footium/blob/main/footium-eth-shareable/contracts/FootiumPrizeDistributor.sol#L109C2-L130C10)

```solidity
    function claimERC20Prize(
        address _to,
        IERC20Upgradeable _token,
        uint256 _amount,
        bytes32[] calldata _proof
    ) external whenNotPaused nonReentrant {
     //...

        // Checks the Merkle proof, which is constructed as a hash of
        // the token address, the receiver address and the amount
        if (
            !MerkleProofUpgradeable.verify(
                _proof,
                erc20MerkleRoot,
                keccak256(abi.encode(_token, _to, _amount))
            )
    //...
```

Prize recipients are the club NFT owners and the decision of the prize recipient is made based on the **owner at the moment when the Merkle tree is created**, not the owner when the league is finished. There will be a time lag between the end of a season and the generation of the Merkle tree since it is generated off-chain. NFT transfers during this time lag will result in different prize recipients.

Malicious users who are aware of this situation might gain an advantage by buying a prize-earner club immediately after the season ends.

Let's imagine this scenario:

* Bob has a club NFT, which is a mid-range club with a league position between 10-13.
    
    The first 9 positions in a league earn prizes [according to the protocol's articles](https://medium.com/footium/footium-prize-pools-fb566f452299).
    
* Bob plays the game but also puts his NFT on sale since the team is not that good and doesn't earn a prize.
    
* Charlie keeps track of the already on-sale but out of the first 9 position teams.
    
* Bob's team suddenly jumps to 8th place in the last match of the league and the league finishes.
    
* Charlie sees this and immediately buys Bob's club NFT, and other NFTs with the same situation.
    
* Merkle tree is generated after this and the prize recipient is Charlie instead of Bob.  
    Bob should be the prize recipient even if he sells his NFT after a season ends
    

From Charlie's perspective, it is like knowing the lottery result before buying a ticket. He won't buy any NFT if none of them reaches the top 9 position, and will buy if there is a profit. There is no risk for Charlie (It is different than buying a **possible** prize-earner club in the last week. In that scenario the results are not certain and there is still a risk). 

The prize recipient should be the club NFT owner **at the timestamp when the league is finished**. Even if the off-chain Merkle tree generation is automated and quick, there will always be a time lag and this lag can be more than enough for a transaction, especially in Arbitrum.

By the way, there doesn't need to be a malicious actor. Just a regular transfer may be finalized between these two timestamps (end of a league / Merkle tree generation).

**Note for judges:** I contacted the sponsor to understand how prize recipients are decided, asked about this situation and got a response saying it is worth raising. I don't like sharing private Discord messages as a screenshot in public submissions, but I can share them with judges if they request.

## Impact

- Prize recipient might be a different person than the one who completed the league.
- Game economy will be affected, leading to user dissatisfaction and trust issues, which harms the protocol in the long-run. 

## Code Snippet
https://github.com/sherlock-audit/2023-12-footium/blob/main/footium-eth-shareable/contracts/FootiumPrizeDistributor.sol#L109C5-L127C14

https://github.com/sherlock-audit/2023-12-footium/blob/main/footium-eth-shareable/contracts/FootiumPrizeDistributor.sol#L155C1-L175C10

## Tool used

Manual Review

## Recommendation
I would recommend fetching the snapshot data of NFT ownerships at the end of the league while generating Merkle trees for prize distribution.

**Comment by osmanozdemir1** [comment]
Escalate

I would agree with the judge's comment if the prizes are directly connected to NFTs. In that case users would know if they sell their NFT before claiming the prize, the prize will be gone with it. 

However, from the users' perspective, just finishing the league and having the NFT at the moment when the league is finished is enough to earn prizes. In the protocol's implementation, users can still claim their prize even if they sell their NFT as long as they had it when the Merkle tree is generated. As we can see [here](https://github.com/sherlock-audit/2023-12-footium/blob/617cbc3df2fb51d9e8e5c701355efec4d4193d55/footium-eth-shareable/contracts/FootiumPrizeDistributor.sol#L116), the only check is being the prize recipient. 

Therefore, selling the NFT **after completing the league** should not change the prize recipient. Prize recipient should be the owner of the NFT **when the league is concluded**. That's why the time lag between "end of the league" and "Merkle tree generation" becomes important. NFT transfer in this specific time period changes the prize recipient even if the league is already concluded, which is not the intended behaviour. 

That's why it creates an attack path for Charlie I mentioned above.
> From Charlie's perspective, it is like knowing the lottery result before buying a ticket. He won't buy any NFT if none of them reaches the top 9 position, and will buy if there is a profit. There is no risk for Charlie (It is different than buying a possible prize-earner club in the last week. In that scenario the results are not certain and there is still a risk).


And lastly, I specifically asked this to sponsor and the response was "That's a valid remark ... better safe than sorry".
Kind regards

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I would agree with the judge's comment if the prizes are directly connected to NFTs. In that case users would know if they sell their NFT before claiming the prize, the prize will be gone with it. 
> 
> However, from the users' perspective, just finishing the league and having the NFT at the moment when the league is finished is enough to earn prizes. In the protocol's implementation, users can still claim their prize even if they sell their NFT as long as they had it when the Merkle tree is generated. As we can see [here](https://github.com/sherlock-audit/2023-12-footium/blob/617cbc3df2fb51d9e8e5c701355efec4d4193d55/footium-eth-shareable/contracts/FootiumPrizeDistributor.sol#L116), the only check is being the prize recipient. 
> 
> Therefore, selling the NFT **after completing the league** should not change the prize recipient. Prize recipient should be the owner of the NFT **when the league is concluded**. That's why the time lag between "end of the league" and "Merkle tree generation" becomes important. NFT transfer in this specific time period changes the prize recipient even if the league is already concluded, which is not the intended behaviour. 
> 
> That's why it creates an attack path for Charlie I mentioned above.
> > From Charlie's perspective, it is like knowing the lottery result before buying a ticket. He won't buy any NFT if none of them reaches the top 9 position, and will buy if there is a profit. There is no risk for Charlie (It is different than buying a possible prize-earner club in the last week. In that scenario the results are not certain and there is still a risk).
> 
> 
> And lastly, I specifically asked this to sponsor and the response was "That's a valid remark ... better safe than sorry".
> Kind regards

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
@osmanozdemir1 

- I disagree, if the original owner of the NFTs knows there is a chance of winning rewards, he will value his NFT appropriately during sale or simply wait for the game to end and claim possible rewards before sale.

- Merkle proof generation is an off-chain mechanism, so it is fair to assume that admins are trusted to generate proofs appropriately for me and other watsons. If not, it will constitute admin error. Discussion between you and the sponsor is not a source of truth, and since it wasn't highlighted to anybody else in the contest details, this should be out of scope for discussion.

- I have provided my reasonings to the sponsor before preliminary results and I think he agrees with me so they can confirm 
@logiclogue @JDansercoer

**Comment by osmanozdemir1** [comment]
@nevillehuang Thanks for the response.

**Comment by Czar102** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [osmanozdemir1](https://github.com/sherlock-audit/2023-12-footium-judging/issues/29/#issuecomment-1867098568): rejected
