### ISSUE TITLE
detectiveking - FootiumClub NFT Seller can Honeypot Buyers

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-footium-judging#53]
detectiveking

high

# FootiumClub NFT Seller can Honeypot Buyers

## Summary

This issue is similar to https://github.com/sherlock-audit/2023-04-footium-judging/issues/291

A FootiumClub NFT seller can honeypot buyers by making them think that there are good academy player NFTs for them to mint after they acquire the club NFT, but then frontrun and mint the academy player NFTs before the buy. 

## Vulnerability Detail

The attack path is as follows:

Requirement: You need a club NFT that has reasonably good mintable academy players

1. List the club NFT for sale
2. Someone sees it and pays a high price for it, after seeing they would be able to mint good academy players after acquiring the club
3. Seller sees the buy transaction in the mempool, and frontruns it with a mint to all the academy player NFTs associated with the club. The academy player NFTs are sent to the malicious seller's address. 
4. Buyer is left with the club NFT but cannot mint any of the valuable academy NFTs, so they have lost a good amount on their investment. 

## Impact

Malicious club NFT seller can honeypot buyers 

## Code Snippet

https://github.com/sherlock-audit/2023-12-footium/blob/main/footium-eth-shareable/contracts/FootiumAcademy.sol#L96-L138

## Tool used

Manual Review

## Recommendation

Implement ERC 721 timelock 

Duplicate of #48

**Comment by anonyloooooooool** [comment]
Escalate

This issue, as well its two duplicates, are valid

To respond to the judge's concerns described here (https://github.com/sherlock-audit/2023-12-footium-judging/issues/48)

1. I believe there is a slight misunderstanding here. You are correct in that if you own a club, you do not own the players. However, you do own the right to mint certain academy players, which is what this issue is referring to. Here is a public statement from the sponsor directly addressing this (near the end of the text):

<img width="1029" alt="Screen Shot 2023-12-21 at 8 46 19 PM" src="https://github.com/sherlock-audit/2023-12-footium-judging/assets/99231099/8c0f82cb-5937-460c-855d-cd735570fa2d">

You can also see this if you read `mintPlayer` in `FootiumAcademy.sol` carefully. The code is as follows:

```
    function mintPlayer(
        uint256 clubId,
        string calldata playerId,
        bytes32[] calldata mintProof
    ) external payable whenNotPaused nonReentrant {
```

You just need a `clubId`, `playerId`, and proof to mint. 

2. You are correct that mempool front-running is not an issue on Arbitrum. However, this issue (https://github.com/sherlock-audit/2023-04-footium-judging/issues/291) was judged as high in spite of this. You can still frontrun if you can guess roughly when the victim will send the transaction, and just bid a higher gas price.
3. Another judge brought up a concern that the mintable academy players for a club may not be shown in the UI. I believe it should be, as it is part of the clubs overall value (as confirmed by the sponsors) and sellers should know it before they buy. Even if it is not, the malicious seller can publish the merkle proofs in the NFT description for example. 

Overall, I do believe this issue is valid, but I believe it to be a medium rather than a high. Ultimately up to @Czar102 though.

**Comment by detectiveking123** [comment]
Escalate

This issue, as well its two duplicates, are valid

To respond to the judge's concerns described here (https://github.com/sherlock-audit/2023-12-footium-judging/issues/48)

1. I believe there is a slight misunderstanding here. You are correct in that if you own a club, you do not own the players. However, you do own the right to mint certain academy players, which is what this issue is referring to. Here is a public statement from the sponsor directly addressing this (near the end of the text):

<img width="1029" alt="Screen Shot 2023-12-21 at 8 46 19 PM" src="https://github.com/sherlock-audit/2023-12-footium-judging/assets/99231099/8c0f82cb-5937-460c-855d-cd735570fa2d">

You can also see this if you read `mintPlayer` in `FootiumAcademy.sol` carefully. The code is as follows:

```
    function mintPlayer(
        uint256 clubId,
        string calldata playerId,
        bytes32[] calldata mintProof
    ) external payable whenNotPaused nonReentrant {
```

You just need a `clubId`, `playerId`, and proof to mint. 

`So there is no point in front-running to mint players, since the original club owner before sale still owns all the players within the club and the buyer can use this players to compete in the game.` <- This statement is actually incorrect; the mintable academy players would actually belong to the club, as you can see from the above code. 

2. You are correct that mempool front-running is not an issue on Arbitrum. However, this issue (https://github.com/sherlock-audit/2023-04-footium-judging/issues/291) was judged as high in spite of this. You can still frontrun if you can guess roughly when the victim will send the transaction.
3. Another judge brought up a concern that the mintable academy players for a club may not be shown in the UI. I believe it should be, as it is part of the clubs overall value (as confirmed by the sponsors) and sellers should know it before they buy. Even if it is not, the malicious seller can publish the merkle proofs in the NFT description for example. 

Overall, I do believe this issue is valid, but I believe it to be a medium rather than a high. Ultimately up to @Czar102 though.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This issue, as well its two duplicates, are valid
> 
> To respond to the judge's concerns described here (https://github.com/sherlock-audit/2023-12-footium-judging/issues/48)
> 
> 1. I believe there is a slight misunderstanding here. You are correct in that if you own a club, you do not own the players. However, you do own the right to mint certain academy players, which is what this issue is referring to. Here is a public statement from the sponsor directly addressing this (near the end of the text):
> 
> <img width="1029" alt="Screen Shot 2023-12-21 at 8 46 19 PM" src="https://github.com/sherlock-audit/2023-12-footium-judging/assets/99231099/8c0f82cb-5937-460c-855d-cd735570fa2d">
> 
> You can also see this if you read `mintPlayer` in `FootiumAcademy.sol` carefully. The code is as follows:
> 
> ```
>     function mintPlayer(
>         uint256 clubId,
>         string calldata playerId,
>         bytes32[] calldata mintProof
>     ) external payable whenNotPaused nonReentrant {
> ```
> 
> You just need a `clubId`, `playerId`, and proof to mint. 
> 
> `So there is no point in front-running to mint players, since the original club owner before sale still owns all the players within the club and the buyer can use this players to compete in the game.` <- This statement is actually incorrect; the mintable academy players would actually belong to the club, as you can see from the above code. 
> 
> 2. You are correct that mempool front-running is not an issue on Arbitrum. However, this issue (https://github.com/sherlock-audit/2023-04-footium-judging/issues/291) was judged as high in spite of this. You can still frontrun if you can guess roughly when the victim will send the transaction.
> 3. Another judge brought up a concern that the mintable academy players for a club may not be shown in the UI. I believe it should be, as it is part of the clubs overall value (as confirmed by the sponsors) and sellers should know it before they buy. Even if it is not, the malicious seller can publish the merkle proofs in the NFT description for example. 
> 
> Overall, I do believe this issue is valid, but I believe it to be a medium rather than a high. Ultimately up to @Czar102 though. 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
> Escalate
> 
> This issue, as well its two duplicates, are valid
> 
> To respond to the judge's concerns described here (#48)
> 
> 1. I believe there is a slight misunderstanding here. You are correct in that if you own a club, you do not own the players. However, you do own the right to mint certain academy players, which is what this issue is referring to. Here is a public statement from the sponsor directly addressing this (near the end of the text):
> 
> <img alt="Screen Shot 2023-12-21 at 8 46 19 PM" width="1029" src="https://private-user-images.githubusercontent.com/99231099/292352577-8c0f82cb-5937-460c-855d-cd735570fa2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMTE1NzgsIm5iZiI6MTcwMzIxMTI3OCwicGF0aCI6Ii85OTIzMTA5OS8yOTIzNTI1NzctOGMwZjgyY2ItNTkzNy00NjBjLTg1NWQtY2Q3MzU1NzBmYTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDAyMTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ODk2NWM5MGUzN2Q1Nzc0ZmE0YTM1MmEzYzYwNmMwNTAwYWVhY2U5ZmQ4OTUzNzE4NzM0YjYyYzVkOTk1YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n0F3oYCvuOQ6kEKCYOb47irVa1D10DAJCZU8A7Bua30">
> You can also see this if you read `mintPlayer` in `FootiumAcademy.sol` carefully. The code is as follows:
> 
> ```
>     function mintPlayer(
>         uint256 clubId,
>         string calldata playerId,
>         bytes32[] calldata mintProof
>     ) external payable whenNotPaused nonReentrant {
> ```
> 
> You just need a `clubId`, `playerId`, and proof to mint.
> 
> `So there is no point in front-running to mint players, since the original club owner before sale still owns all the players within the club and the buyer can use this players to compete in the game.` <- This statement is actually incorrect; the mintable academy players would actually belong to the club, as you can see from the above code.
> 
> 2. You are correct that mempool front-running is not an issue on Arbitrum. However, this issue ([0x52 - Malicious users can honeypot other users by transferring out ERC20 and ERC721 tokens right before sale 2023-04-footium-judging#291](https://github.com/sherlock-audit/2023-04-footium-judging/issues/291)) was judged as high in spite of this. You can still frontrun if you can guess roughly when the victim will send the transaction.
> 3. Another judge brought up a concern that the mintable academy players for a club may not be shown in the UI. I believe it should be, as it is part of the clubs overall value (as confirmed by the sponsors) and sellers should know it before they buy. Even if it is not, the malicious seller can publish the merkle proofs in the NFT description for example.
> 
> Overall, I do believe this issue is valid, but I believe it to be a medium rather than a high. Ultimately up to @Czar102 though.

Because front-running is a non-issue on arbitrum all other reason shouldn’t matter unless sponsor wants to clarify. “Guessing transactions” is not a valid reason for validating.

**Comment by detectiveking123** [comment]
By that logic https://github.com/sherlock-audit/2023-04-footium-judging/issues/291 should be invalid

I said that mempool front-running isn't an issue. There's a difference between mem-pool front-running and general front-running. Mempool front-running is seeing a transaction in the mempool and front-running it. General front-running can be done in many ways -- what I described to you is a valid way to front-run and you see it with token snipers all the time.

**Comment by detectiveking123** [comment]
Here's a valid attack for example: 

1. You have a club that has the right to mint 10 highly coveted legendary academy players. The club + 10 academy players is easily worth 10 ETH total. 
2. You put the club NFT up for sale at 8 ETH, knowing it will surely be almost immediately taken.
3. You guess it will be taken in 30 seconds and are correct and land on the same block -- you mint the legendary academy players for yourself but the buy still goes through right afterward, so the buyer is down a lot of money.

**Comment by nevillehuang** [comment]
@detectiveking123 fair point,

@Czar102 why was the previous issue [here](https://github.com/sherlock-audit/2023-04-footium-judging/issues/291) accepted as an issue when there is no mempool on arbitrum? To me both issues should be invalid. To my knowledge, front-running issues in Arbitrum has always been rejected in both sherlock and other platforms such as C4 historically. See [here](https://docs.arbitrum.io/learn-more/faq#does-arbitrum-have-a-mempool):

> The Arbitrum Sequencer orders transactions on a first come, first served basis; the Sequencer inserts transactions into a queue based on the order they are received and executes them accordingly. This queue thus exists in lieu of a mempool. The Sequencer's queue has no space limit; transactions on the queue will eventually timeout and be discarded if not executed in time. Under normal conditions, the queue is empty, since transactions are executed near-instantaneously.

There is no mempool so how do you even make a reasonable guess to front-run? In the context of this protocol, it is certainly not profitable.

**Comment by detectiveking123** [comment]
`There is no mempool so how do you even make a reasonable guess to front-run? In the context of this protocol, it is certainly not profitable.`

As described above, if I were the attacker, I'd give a good price so someone would be baited into buying almost instantly. I can then narrow down the time that they'll buy to sometime in the next few minutes, which would give me a nontrivial chance of frontrunning them.

**Comment by nevillehuang** [comment]
> `There is no mempool so how do you even make a reasonable guess to front-run? In the context of this protocol, it is certainly not profitable.`
> 
> As described above, if I were the attacker, I'd give a good price so someone would be baited into buying almost instantly. I can then narrow down the time that they'll buy to sometime in the next few minutes, which would give me a nontrivial chance of frontrunning them.

To me this is just speculating on when the buyer will actually submit the transaction to buy. Imo, the guessing game is too difficult to warrant this as a medium severity finding, even more so when you don't know which transactions will overtake you since there are so many transactions submitted to the arbitrum sequencer.

**Comment by detectiveking123** [comment]
My opinion is that issues where the malicious attacker needs to see the user transaction before constructing their own transaction should be invalid on Arbitrum, since **mempool** frontrunning is nonexistent (though frontrunning does exist!). 

However, in this case, the attacker can send their own front-run transaction without even seeing the user transaction (but they just have to get lucky with placement). This distinction turns this issue into a valid attack, in my opinion.

**Comment by nevillehuang** [comment]
@detectiveking123 

The seller of the club needs to see the buyer sending the transaction to buy the NFT so I think your points contradict each other.

**Comment by detectiveking123** [comment]
That's not what I mean, malicious sender can still construct their transaction without seeing the user transaction.

**Comment by BoRonG0d** [comment]
> Here's a valid attack for example:
> 
> 1. You have a club that has the right to mint 10 highly coveted legendary academy players. The club + 10 academy players is easily worth 10 ETH total.
> 2. You put the club NFT up for sale at 8 ETH, knowing it will surely be almost immediately taken.
> 3. You guess it will be taken in 30 seconds and are correct and land on the same block -- you mint the legendary academy players for yourself but the buy still goes through right afterward, so the buyer is down a lot of money.

![image](https://github.com/sherlock-audit/2023-12-footium-judging/assets/119436006/e5b08edd-2019-4da3-8fde-07b4054ad75f)

3000Clubs would generate 30000 players to be claimed every game season. I wonder how much impact can this attack have.

**Comment by nevillehuang** [comment]
@detectiveking123 Im still unsure what you are trying to explain here but I believe my points in our discussion are sufficient to support my stance of invalidation. Will leave it to @Czar102 to decide final validity.

**Comment by Czar102** [comment]
Are the markets on which these trades happen native to footium or are they secondary?

**Comment by detectiveking123** [comment]
I don't think there are Footium native NFT markets at the moment. As described in this previous issue (https://github.com/sherlock-audit/2023-04-footium-judging/issues/378), the markets in which the buy/sell trades happen would be secondary markets like OpenSea, where Footium has a listing.

**Comment by BoRonG0d** [comment]
Even if the "Guess Frontrun" is feasible, I believe this should be low.

According to the sponsor, there is no difference in the players minted in Academy.

![image](https://github.com/sherlock-audit/2023-12-footium-judging/assets/119436006/06feeff1-cf3b-48b7-8cc8-f1c9a145f35c)

And, according to Footium's [doc](https://footium.gitbook.io/footium-wiki/assets-breakdown/clubs/academy),

> To guarantee that you keep an academy product at your club past the age of 21, you will need to sign them as a squad player – by minting him as an NFT. 
Failure to do so will mean that the player becomes a free agent, and any other club will be able to sign him at an auction. Once you've signed a player, you have the scope to sell and loan them out to other teams or continue playing them in your squad.

Unable to mint in one's own Academy doesn't seem like a issue, they can just sigh other palyers since they're the same.

**Comment by detectiveking123** [comment]
1. Not sure that really matters, you still lose out on the academy players. Also, NFTs are inherently distinct, so some will surely be valued more than others regardless
2. Wouldn't you still have to pay more for the other players than you would if you just minted through your own academy?

**Comment by Czar102** [comment]
If the speculation is done on the way people transact on the secondary markets, I don't think it is fair to assume that buyers wouldn't prevent minting players by the seller. The submission is based on the buyer making an incorrect assumption that the club can't lose value (change state) while listed, which (as shown in the submission) is obviously false.

I plan to reject the escalation on the above basis, unless it was mentioned in the code/docs that the clubs were intended to trade on the secondary markets without any kind of escrow, and they should preserve their state during the listing. (or any other reason why would the above reason not apply here)
cc @detectiveking123

**Comment by anonyloooooooool** [comment]
@Czar102 Let me look into the provided documentation a bit more, I will respond in a few hours.

**Comment by detectiveking123** [comment]
@Czar102 The fact that the secondary markets exist should be determinable through the publicly available resources provided during the contest. For example, https://footium.club/ has an OpenSea listing (and this link was provided by one of the sponsors publicly in the Discord). 

Here is also a public statement from one of the sponsors that both implies secondary markets are important to Footium and should also address your other point to some extent. 

<img width="1019" alt="Screen Shot 2024-01-01 at 8 02 49 PM" src="https://github.com/sherlock-audit/2023-12-footium-judging/assets/99231099/d2eafa23-ad45-4062-8545-3f08c28a44b7">

But ultimately, the basis of honeypot attacks is making users think there is value when you have the ability to just swipe it away. You are correct in that in a perfect world, the buyer would be a sophisticated smart contract that can tell when academy players for the club have already been minted, and just not buy in that case. But generally users in the real world are much less sophisticated and historically honeypotting attacks like these have been considered valid by Sherlock. 

In fact, if we were to assume that users were super sophisticated and made absolutely no mistakes, no frontrunning / sandwich attack should ever be valid (at least on Ethereum), since Flashbots can just be used. 

Will respect your decision either way, but in the event this issue is invalidated, I would appreciate some further clarification in the Sherlock rules about when specifically honeypot attacks are considered valid.

**Comment by nevillehuang** [comment]
Since arbitrum has no mempool, for a seller to front run a buyers transaction buying to mint, it would need the seller to take absolute pure speculation and guessing. For that reason, this should be invalid. 

Historically, sherlock has always invalidate arbitrum front running issues (not going to find examples for now but you can look it up). Im honestly quite puzzled why the previous issue was accepted since it mentions mempool (current issue also mentions mempool), when arbitrum has no mempool at all, so the attack scenario described is incorrect

**Comment by detectiveking123** [comment]
@nevillehuang Could you find at least one example to support your claim? There's an existing example ([the similar issue in previous Footium audit contest)](https://github.com/sherlock-audit/2023-04-footium-judging/issues/291) where the front-running issue was validated on Arbitrum.

**Comment by 0xEVom** [comment]
> Another judge brought up a concern that the mintable academy players for a club may not be shown in the UI. I believe it should be, as it is part of the clubs overall value (as confirmed by the sponsors) and sellers should know it before they buy. > Even if it is not, the malicious seller can publish the merkle proofs in the NFT description for example.

With regards to this and the general argument on unminted players constituting part of the club's overall value, I think this relies on an assumption that was not stated in the docs. All the sponsor's comment above says is:

> The only thing that's tied to the club, is the right to mint academy players and the club's stadium (stadium is off-chain at the moment though).

Which doesn't directly imply _specific_ unminted players are part of the value a club.

If a malicious seller publishes the Merkle proofs as part of the listing, then they are definitely relying on a mechanism that was not part of the project's original logic and the buyer is taking a risk by relying on this information.

**Comment by detectiveking123** [comment]
"The only thing that's tied to the club, is the right to mint academy players" -> This seems like a direct implication to me. ERC721 tokens are non-fungible by nature, so every club will have the ability to mint different academy players (at least with a different name and face, even if there are no legendaries), which will be subjectively valued by the market.

**Comment by 0xEVom** [comment]
Even a club with no pending unminted players (at the moment) still has a right to mint academy players tied to it (in the future).

**Comment by detectiveking123** [comment]
Ah I see what you mean. Every club starts with the ability to mint 10 academy players; this is in both the publicly available and distributed Footium docs and video.

**Comment by nevillehuang** [comment]
@detectiveking123 I'll try to find it when I have the time, but it is not wrong to say that this issues "vulnerability details" section is completely invalid, so only the "summary" section can "possibly" make sense, which in turn would not be unfair to say no sufficient and clear attack path is highlighted. Same goes for the previous highlighted issue, which I feel is incorrectly judged, given you can't "see" transactions in the mempool when there is no mempool.

**Comment by Czar102** [comment]
> The fact that the secondary markets exist should be determinable through the publicly available resources provided during the contest.

Not only no, but you also can't justify the implication (secondary markets exist ==> people on these secondary markets are told to assume the current owner can't impact their valuation and that they care about whether player NFTs are minted or not – maybe they just care about the club logo?).

> I would appreciate some further clarification in the Sherlock rules about when specifically honeypot attacks are considered valid.

They are not valid if you assume that users are not sophisticated. Honeypotting would be valid if the documentation directly contradicted with the current behavior (like I said in the previous message), or if the property that is broken would be obvious to be supposed to hold, which is not the case here.

Else, like in this case, honeypotting is a good informational issue. Tagging @JDansercoer to make sure the team is aware of this property of the system.

**Comment by Czar102** [comment]
Result:
Invalid
Duplicate of #48

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [detectiveking123](https://github.com/sherlock-audit/2023-12-footium-judging/issues/53/#issuecomment-1867136510): rejected
