### ISSUE TITLE
0xMaroutis - Club Owner can mint the same `playerId` string if timed correctly

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-footium-judging#93]
0xMaroutis

medium

# Club Owner can mint the same `playerId` string if timed correctly

## Summary

A club owner can mint the same `playerId` string twice by exploiting the timing of the minting process. This issue stems from the specific method of generating `playerId` strings.

## Vulnerability Detail

The `playerId` string is constructed using a combination of the `tokenId` (clubId), the `playerId` token counter, and the index in the initial minting sequence (`i` in the `FootiumClubMinter::mint` function). For example, a `playerId` could be "10-120-2". This information is sent through the event to the offchain process to generate the playeId string. However, there's a timing vulnerability:

A club owner first mints a player with a specific `playerId` string using `mintPlayer`. Let's say "11-122-2".
The club owner then times the `FootiumClubMinter::mint` function call when the token counter is at a specific value (e.g., 122) to create a new club.
During the minting process of the new club (clubId = 11), when the index `i` reaches the same value as in the first minting (e.g., 2), and the token counter aligns (e.g., becomes 120), the same `playerId` (e.g., "11-122-2") gets generated again. 

## Impact

This issue allows club owners to create duplicate `playerId` strings, leading to same player duplication which can impact the fairness of the game

## Code Snippet
https://github.com/sherlock-audit/2023-12-footium/blob/main/footium-eth-shareable/contracts/FootiumAcademy.sol#L124-L126

https://github.com/sherlock-audit/2023-12-footium/blob/main/footium-eth-shareable/contracts/FootiumClubMinter.sol#L78

## Tool used

Manual Review

## Recommendation

The `FootiumAcademy::mintPlayer` checks if a playerId has been minted before `require(_mintedPlayers[playerId] == false, "Player already minted");`. It may be also require to check if a player has been minted before in the `FootiumClubMinter::mint` function and increase the tokenId or the index if that is the case.

**Comment by Maroutis** [comment]
[ESCALATION]

I believe there is a misunderstanding regarding this issue. There are 3 different notations here :

- **PlayerId Token Counter**: Used in the `FootiumClubMinter` contract ([source](https://github.com/sherlock-audit/2023-12-footium/blob/617cbc3df2fb51d9e8e5c701355efec4d4193d55/footium-eth-shareable/contracts/FootiumClubMinter.sol#L75)).
- **PlayerAssetId Token Counter**: Used in the `FootiumAcademy` contract ([source](https://github.com/sherlock-audit/2023-12-footium/blob/617cbc3df2fb51d9e8e5c701355efec4d4193d55/footium-eth-shareable/contracts/FootiumAcademy.sol#L124)).
- **PlayerId String Representation**: A combination of the tokenId (clubId), the playerId token counter, and the index in the initial minting sequence, as seen in the `FootiumAcademy` contract ([source](https://github.com/sherlock-audit/2023-12-footium/blob/617cbc3df2fb51d9e8e5c701355efec4d4193d55/footium-eth-shareable/contracts/FootiumAcademy.sol#L98C25-L98C33)).

The sponsor indicates that the playerId string representation is derived from the combination of the tokenId (clubId), the playerId token counter, and the index in the initial minting sequence (`i` in the `FootiumClubMinter::mint` function). . According to the sponsor, when an `InitialPlayerMinted` event is emitted, it allows the reconstruction of the playerId string representation for the 20 newly minted players thanks to it's values. In this scenario, each playerId token counter minted matches the one in the string representation.

However, this is not the case when using the `mintPlayer` function. If the `playerAssetId` token counter of the playerId string parameter matches the next token counter, another user could potentially mint their player first, or the Owner could create a new club with 20 players for another user. In such a case, when you attempt to call `mintPlayer`, the tokenCounter would have already increased, differing from the one used in the playerId string representation. Since the `clubId` used in the string `playerId` can vary, there is a risk that the Owner might mint the same player for another user or the same user, even though the token increments are not identical, the string representation could be the same.

Furthermore, if the playerId string representation given off-chain to the user contains a token increment that is far ahead, then by precisely timing when the token counter will be reached, a user can request the owner to create a new `clubId` (reflecting the one used in the `playerId` string). Consequently, one of the 20 players minted in this new club could have the same increment used in the playerId string representation. The event emitted would then recreate the same exact player.

In off-chain process, it's the string representation of the player that matters not the token counter (unless if it is used to reconstruct this representation like in `FootiumClubMinter::mint`. This issue would then highlight a potential player duplication.

**Comment by sherlock-admin2** [comment]
> ESCALATED
> 
> I believe there is a misunderstanding regarding this issue. There are 3 different notations here :
> 
> - **PlayerId Token Counter**: Used in the `FootiumClubMinter` contract ([source](https://github.com/sherlock-audit/2023-12-footium/blob/617cbc3df2fb51d9e8e5c701355efec4d4193d55/footium-eth-shareable/contracts/FootiumClubMinter.sol#L75)).
> - **PlayerAssetId Token Counter**: Used in the `FootiumAcademy` contract ([source](https://github.com/sherlock-audit/2023-12-footium/blob/617cbc3df2fb51d9e8e5c701355efec4d4193d55/footium-eth-shareable/contracts/FootiumAcademy.sol#L124)).
> - **PlayerId String Representation**: A combination of the tokenId (clubId), the playerId token counter, and the index in the initial minting sequence, as seen in the `FootiumAcademy` contract ([source](https://github.com/sherlock-audit/2023-12-footium/blob/617cbc3df2fb51d9e8e5c701355efec4d4193d55/footium-eth-shareable/contracts/FootiumAcademy.sol#L98C25-L98C33)).
> 
> The sponsor indicates that the playerId string representation is derived from the combination of the tokenId (clubId), the playerId token counter, and the index in the initial minting sequence (`i` in the `FootiumClubMinter::mint` function). . According to the sponsor, when an `InitialPlayerMinted` event is emitted, it allows the reconstruction of the playerId string representation for the 20 newly minted players thanks to it's values. In this scenario, each playerId token counter minted matches the one in the string representation.
> 
> However, this is not the case when using the `mintPlayer` function. If the `playerAssetId` token counter of the playerId string parameter matches the next token counter, another user could potentially mint their player first, or the Owner could create a new club with 20 players for another user. In such a case, when you attempt to call `mintPlayer`, the tokenCounter would have already increased, differing from the one used in the playerId string representation. Since the `clubId` used in the string `playerId` can vary, there is a risk that the Owner might mint the same player for another user or the same user, even though the token increments are not identical, the string representation could be the same.
> 
> Furthermore, if the playerId string representation given off-chain to the user contains a token increment that is far ahead, then by precisely timing when the token counter will be reached, a user can request the owner to create a new `clubId` (reflecting the one used in the `playerId` string). Consequently, one of the 20 players minted in this new club could have the same increment used in the playerId string representation. The event emitted would then recreate the same exact player.
> 
> In off-chain process, it's the string representation of the player that matters not the token counter (unless if it is used to reconstruct this representation like in `FootiumClubMinter::mint`. This issue would then highlight a potential player duplication.

    You've deleted an escalation for this issue.

**Comment by nevillehuang** [comment]
@Maroutis 

I get what you are saying now, sorry for the slightly wrong invalidation reasoning for this issue. However, the reasoning is not completely wrong.

For a user to call `mintPlayer()` with a valid merkle proof verified `playerID`, the admin would first have to mint a club to the user via `mint()`. This means `playerId` and `playerAssetId` will both be new values after tokenId is incremented in safeMint, so duplicate playerId strings are never possible.

I.e in your example you cannot reach the tokenId 122 twice as it is always incremented when a footium player is minted.

**Comment by Maroutis** [comment]
@nevillehuang 

Thank you for the reply. However, this wasn't the scenario I considered. 

The player would already have a club with players. He also have a valid merkle proof verified `playerID` with an index in the future. By precisely timing when the token counter will be reached, the user can request the owner to create a new  `clubId ` (reflecting the one used in the playerId string). One of the new players will have the same token counter + index of the `playerId` string. Or, the owner can create the new club for another player who would also have the same player.

**Comment by nevillehuang** [comment]
@Maroutis 

Your above point is invalid as duplicate clubIds represented by `tokenId` in `mint()` cannot be minted to the same player due to innate duplicate checks within safeMint().

TLDR, there can never be duplicate clubIds or playerIds so a duplicate playerId string is not possible.

I suggest you to verify with a coded PoC, but I am pretty sure this issue is invalid.

**Comment by Maroutis** [comment]
@nevillehuang 

Agreed but wasn't thinkin about duplicate `clubIds`. There doesn't seem to be a clear cut rules regarding the `clubId` used in the `playerId` string. This variable is mostly used to verify the proof. I believe `clubId` could be anything as long as it satisfies the proof verification. And in most cases where clubId is a number that hasn't been minted before, the duplication is possible.

**Comment by nevillehuang** [comment]
@Maroutis 

Since the playerId string must be explicitly verified by the off-chain merkle proof set by admin to user minting for existing clubs, it will only be possible when admin generates merkle proof incorrectly, which is not valid based on sherlock rules since it would constitute admin error.

**Comment by Maroutis** [comment]
@nevillehuang 

Agreed, if the verification handles both `clubId` and `playerId` counter so that they can be duplicated when used together then it wouldn't constitute an issue. But wasn't clear cut in the docs. 

Thanks for the reply !

**Comment by nevillehuang** [comment]
@Maroutis no problem if you are convinced of my reason for invalidation, you can delete your escalation to avoid the potential of it being rejected.

If not feel free to leave it escalated if you are still not convinced. Thank you for your understanding 👍
